import { NextResponse } from 'next/server';
import { Region } from '@/src/components/properties.type';

const regionsData: Region[] = [
  {
    id: "wellington",
    name: "Wellington",
    cities: [
      {
        id: "wellington-city",
        name: "Wellington City",
        suburbs: [
          { id: "aro valley", name: "Aro Valley" },
          { id: "berhampore", name: "Berhampore" },
          { id: "brooklyn", name: "Brooklyn" },
          { id: "crofton downs", name: "Crofton Downs" },
          { id: "glenside", name: "Glenside" },
          { id: "hataitai", name: "Hataitai" },
          { id: "highbury", name: "Highbury" },
          { id: "horokiwi", name: "Horokiwi" },
          { id: "houghton bay", name: "Houghton Bay" },
          { id: "johnsonville", name: "Johnsonville" },
          { id: "karori", name: "Karori" },
          { id: "kelburn", name: "Kelburn" },
          { id: "khandallah", name: "Khandallah" },
          { id: "kilbirnie", name: "Kilbirnie" },
          { id: "lyall bay", name: "Lyall Bay" },
          { id: "melrose", name: "Melrose" },
          { id: "miramar", name: "Miramar" },
          { id: "mornington", name: "Mornington" },
          { id: "mount cook", name: "Mount Cook" },
          { id: "mount victoria", name: "Mount Victoria" },
          { id: "newtown", name: "Newtown" },
          { id: "ngaio", name: "Ngaio" },
          { id: "ngauranga", name: "Ngauranga" },
          { id: "northland", name: "Northland" },
          { id: "ohariu", name: "Ohariu" },
          { id: "oriental bay", name: "Oriental Bay" },
          { id: "paparangi", name: "Paparangi" },
          { id: "rongotai", name: "Rongotai" },
          { id: "roseneath", name: "Roseneath" },
          { id: "seatoun", name: "Seatoun" },
          { id: "strathmore park", name: "Strathmore Park" },
          { id: "takapu valley", name: "Takapu Valley" },
          { id: "tawa", name: "Tawa" },
          { id: "thorndon", name: "Thorndon" },
          { id: "wadestown", name: "Wadestown" },
          { id: "wellington central", name: "Wellington Central" },
          { id: "wilton", name: "Wilton" }
        ]
      },
      {
        id: "porirua-city",
        name: "Porirua City",
        suburbs: [
          { id: "aotea", name: "Aotea" },
          { id: "colonial knob", name: "Colonial Knob" },
          { id: "keneuru", name: "Keneuru" },
          { id: "pauatahanui", name: "Pauatahanui" },
          { id: "ranui", name: "Ranui" },
          { id: "whitby", name: "Whitby" },
          { id: "ascot park", name: "Ascot Park" },
          { id: "elsdon", name: "Elsdon" },
          { id: "paekakariki hill", name: "Paekakariki Hill" },
          { id: "plimmerton", name: "Plimmerton" },
          { id: "takapuwahia", name: "Takapuwahia" },
          { id: "camborne", name: "Camborne" },
          { id: "hongoekea", name: "Hongoekea" },
          { id: "papakowhai", name: "Papakowhai" },
          { id: "porirua city centre", name: "Porirua City Centre" },
          { id: "titahi bay", name: "Titahi Bay" },
          { id: "cannons creek", name: "Cannons Creek" },
          { id: "judgeford", name: "Judgeford" },
          { id: "paremata", name: "Paremata" },
          { id: "pukerua bay", name: "Pukerua Bay" },
          { id: "waitangirua", name: "Waitangirua" }
        ]
      },
      {
        id: "lower-hutt-city",
        name: "Lower Hutt City",
        suburbs: [
          { id: "alicetown", name: "Alicetown" },
          { id: "avalon", name: "Avalon" },
          { id: "belmont", name: "Belmont" },
          { id: "boulcott", name: "Boulcott" },
          { id: "days bay", name: "Days Bay" },
          { id: "eastbourne", name: "Eastbourne" },
          { id: "epuni", name: "Epuni" },
          { id: "fairfield", name: "Fairfield" },
          { id: "gracefield", name: "Gracefield" },
          { id: "harbour view", name: "Harbour View" },
          { id: "haywards", name: "Haywards" },
          { id: "hutt central", name: "Hutt Central" },
          { id: "kelson", name: "Kelson" },
          { id: "korokoro", name: "Korokoro" },
          { id: "lowry bay", name: "Lowry Bay" },
          { id: "mahina bay", name: "Mahina Bay" },
          { id: "manor park", name: "Manor Park" },
          { id: "matiu somes island", name: "Matiu / Somes Island" },
          { id: "maungaraki", name: "Maungaraki" },
          { id: "melling", name: "Melling" },
          { id: "moera", name: "Moera" },
          { id: "naenae", name: "Naenae" },
          { id: "normandale", name: "Normandale" },
          { id: "pencarrow head", name: "Pencarrow Head" },
          { id: "petone", name: "Petone" },
          { id: "point howard", name: "Point Howard" },
          { id: "remutaka forest park", name: "Remutaka Forest Park" },
          { id: "seaview", name: "Seaview" },
          { id: "sorrento bay", name: "Sorrento Bay" },
          { id: "stokes valley", name: "Stokes Valley" },
          { id: "sunshine bay", name: "Sunshine Bay" },
          { id: "taita", name: "Taita" },
          { id: "tirohanga", name: "Tirohanga" },
          { id: "wainuiomata", name: "Wainuiomata" },
          { id: "wainuiomata coast", name: "Wainuiomata Coast" },
          { id: "waiwhetu", name: "Waiwhetu" },
          { id: "waterloo", name: "Waterloo" },
          { id: "woburn", name: "Woburn" },
          { id: "york bay", name: "York Bay" }
        ]
      },
      {
        id: "upper-hutt-city",
        name: "Upper Hutt City",
        suburbs: [
          { id: "akatarawa", name: "Akatarawa" },
          { id: "akatarawa valley", name: "Akatarawa Valley" },
          { id: "birchville", name: "Birchville" },
          { id: "blue mountains", name: "Blue Mountains" },
          { id: "brown owl", name: "Brown Owl" },
          { id: "clouston park", name: "Clouston Park" },
          { id: "craigs flat", name: "Craigs Flat" },
          { id: "ebdentown", name: "Ebdentown" },
          { id: "elderslea", name: "Elderslea" },
          { id: "heretaunga", name: "Heretaunga" },
          { id: "kaitoke", name: "Kaitoke" },
          { id: "kingsley heights", name: "Kingsley Heights" },
          { id: "maidstone", name: "Maidstone" },
          { id: "mangaroa", name: "Mangaroa" },
          { id: "maoribank", name: "Maoribank" },
          { id: "maymorn", name: "Maymorn" },
          { id: "moonshine valley", name: "Moonshine Valley" },
          { id: "pinehaven", name: "Pinehaven" },
          { id: "remutaka hill", name: "Remutaka Hill" },
          { id: "riverstone terraces", name: "Riverstone Terraces" },
          { id: "silverstream", name: "Silverstream" },
          { id: "te marua", name: "Te Marua" },
          { id: "timberlea", name: "Timberlea" },
          { id: "totara park", name: "Totara Park" },
          { id: "trentham", name: "Trentham" },
          { id: "upper hutt central", name: "Upper Hutt Central" },
          { id: "wallaceville", name: "Wallaceville" },
          { id: "whitemans valley", name: "Whitemans Valley" }
        ]
      },
      {
        id: "kapiti-coast-district",
        name: "Kapiti Coast District",
        suburbs: [
          { id: "akatarawa valley", name: "Akatarawa Valley" },
          { id: "birchville", name: "Birchville" },
          { id: "blue mountains", name: "Blue Mountains" },
          { id: "clouston park", name: "Clouston Park" },
          { id: "craigs flat", name: "Craigs Flat" },
          { id: "ebdentown", name: "Ebdentown" },
          { id: "heretaunga", name: "Heretaunga" },
          { id: "kaitoke", name: "Kaitoke" },
          { id: "kingsley heights", name: "Kingsley Heights" },
          { id: "mangaroa", name: "Mangaroa" },
          { id: "maoribank", name: "Maoribank" },
          { id: "maymorn", name: "Maymorn" },
          { id: "pinehaven", name: "Pinehaven" },
          { id: "remutaka hill", name: "Remutaka Hill" },
          { id: "riverstone terraces", name: "Riverstone Terraces" },
          { id: "te marua", name: "Te Marua" },
          { id: "timberlea", name: "Timberlea" },
          { id: "upper hutt central", name: "Upper Hutt Central" },
          { id: "wallaceville", name: "Wallaceville" },
          { id: "whitemans valley", name: "Whitemans Valley" }
        ]
      }
    ]
  },
  {
    id: "auckland",
    name: "Auckland",
    cities: [
      {
        id: "auckland-city",
        name: "Auckland - City",
        suburbs: [
          { id: "auckland central", name: "Auckland Central" },
          { id: "avondale", name: "Avondale" },
          { id: "bayswater", name: "Bayswater" },
          { id: "blockhouse bay", name: "Blockhouse Bay" },
          { id: "devonport", name: "Devonport" },
          { id: "eden terrace", name: "Eden Terrace" },
          { id: "ellerslie", name: "Ellerslie" },
          { id: "epsom", name: "Epsom" },
          { id: "freemans bay", name: "Freemans Bay" },
          { id: "glen innes", name: "Glen Innes" },
          { id: "glendowie", name: "Glendowie" },
          { id: "grafton", name: "Grafton" },
          { id: "great barrier island", name: "Great Barrier Island (Aotea Island)" },
          { id: "greenlane", name: "Greenlane" },
          { id: "grey lynn", name: "Grey Lynn" },
          { id: "herne bay", name: "Herne Bay" },
          { id: "hillsborough", name: "Hillsborough" },
          { id: "howick", name: "Howick" },
          { id: "kingsland", name: "Kingsland" },
          { id: "kohimarama", name: "Kohimarama" },
          { id: "leigh", name: "Leigh" },
          { id: "lynfield", name: "Lynfield" },
          { id: "manurewa", name: "Manurewa" },
          { id: "meadowbank", name: "Meadowbank" },
          { id: "mission bay", name: "Mission Bay" },
          { id: "morningside", name: "Morningside" },
          { id: "motutapu island", name: "Motutapu Island" },
          { id: "mount albert", name: "Mount Albert" },
          { id: "mount eden", name: "Mount Eden" },
          { id: "mount roskill", name: "Mount Roskill" },
          { id: "mount wellington", name: "Mount Wellington" },
          { id: "new windsor", name: "New Windsor" },
          { id: "newmarket", name: "Newmarket" },
          { id: "northcote", name: "Northcote" },
          { id: "omaha", name: "Omiha" },
          { id: "one tree hill", name: "One Tree Hill" },
          { id: "onehunga", name: "Onehunga" },
          { id: "oneroa", name: "Oneroa" },
          { id: "onetangi", name: "Onetangi" },
          { id: "orakei", name: "Orakei" },
          { id: "orewa", name: "Orewa" },
          { id: "ostend", name: "Ostend" },
          { id: "otahuhu", name: "Otahuhu" },
          { id: "palm beach", name: "Palm Beach" },
          { id: "panmure", name: "Panmure" },
          { id: "papakura", name: "Papakura" },
          { id: "papatoetoe", name: "Papatoetoe" },
          { id: "parnell", name: "Parnell" },
          { id: "penrose", name: "Penrose" },
          { id: "point chevalier", name: "Point Chevalier" },
          { id: "point england", name: "Point England" },
          { id: "ponsonby", name: "Ponsonby" },
          { id: "ponui island", name: "Ponui Island / Chamberlins Island" },
          { id: "pukekohe", name: "Pukekohe" },
          { id: "rakino island", name: "Rakino Island" },
          { id: "remuera", name: "Remuera" },
          { id: "royal oak", name: "Royal Oak" },
          { id: "saint heliers", name: "Saint Heliers" },
          { id: "saint johns", name: "Saint Johns" },
          { id: "saint marys bay", name: "Saint Marys Bay" },
          { id: "sandringham", name: "Sandringham" },
          { id: "stonefields", name: "Stonefields" },
          { id: "surfdale", name: "Surfdale" },
          { id: "te atatu peninsula", name: "Te Atatu Peninsula" },
          { id: "three kings", name: "Three Kings" },
          { id: "wai o taiki bay", name: "Wai O Taiki Bay" },
          { id: "waiheke island", name: "Waiheke Island" },
          { id: "waiuku", name: "Waiuku" },
          { id: "waterview", name: "Waterview" },
          { id: "wesley", name: "Wesley" },
          { id: "western springs", name: "Western Springs" },
          { id: "westhaven", name: "Westhaven" },
          { id: "westmere", name: "Westmere" }
        ]
      },
      {
        id: "auckland-north-shore",
        name: "Auckland - North Shore",
        suburbs: [
          { id: "albany", name: "Albany" },
          { id: "albany heights", name: "Albany Heights" },
          { id: "auckland central", name: "Auckland Central" },
          { id: "bayswater", name: "Bayswater" },
          { id: "bayview", name: "Bayview" },
          { id: "beach haven", name: "Beach Haven" },
          { id: "belmont", name: "Belmont" },
          { id: "birkdale", name: "Birkdale" },
          { id: "birkenhead", name: "Birkenhead" },
          { id: "browns bay", name: "Browns Bay" },
          { id: "campbells bay", name: "Campbells Bay" },
          { id: "castor bay", name: "Castor Bay" },
          { id: "chatswood", name: "Chatswood" },
          { id: "devonport", name: "Devonport" },
          { id: "epsom", name: "Epsom" },
          { id: "fairview heights", name: "Fairview Heights" },
          { id: "forrest hill", name: "Forrest Hill" },
          { id: "glenfield", name: "Glenfield" },
          { id: "greenhithe", name: "Greenhithe" },
          { id: "grey lynn", name: "Grey Lynn" },
          { id: "hauraki", name: "Hauraki" },
          { id: "hillcrest", name: "Hillcrest" },
          { id: "long bay", name: "Long Bay" },
          { id: "lucas heights", name: "Lucas Heights" },
          { id: "mairangi bay", name: "Mairangi Bay" },
          { id: "milford", name: "Milford" },
          { id: "mount eden", name: "Mount Eden" },
          { id: "murrays bay", name: "Murrays Bay" },
          { id: "narrow neck", name: "Narrow Neck" },
          { id: "northcote", name: "Northcote" },
          { id: "northcote point", name: "Northcote Point" },
          { id: "northcross", name: "Northcross" },
          { id: "okura", name: "Okura" },
          { id: "oteha", name: "Oteha" },
          { id: "papatoetoe", name: "Papatoetoe" },
          { id: "paremoremo", name: "Paremoremo" },
          { id: "pinehill", name: "Pinehill" },
          { id: "rosedale", name: "Rosedale" },
          { id: "rothesay bay", name: "Rothesay Bay" },
          { id: "schnapper rock", name: "Schnapper Rock" },
          { id: "stanley point", name: "Stanley Point" },
          { id: "sunnynook", name: "Sunnynook" },
          { id: "takapuna", name: "Takapuna" },
          { id: "torbay", name: "Torbay" },
          { id: "totara vale", name: "Totara Vale" },
          { id: "unsworth heights", name: "Unsworth Heights" },
          { id: "waiake", name: "Waiake" },
          { id: "wairau valley", name: "Wairau Valley" },
          { id: "windsor park", name: "Windsor Park" }
        ]
      },
      {
        id: "auckland-papakura",
        name: "Auckland - Papakura",
        suburbs: [
          { id: "alfriston", name: "Alfriston" },
          { id: "ardmore", name: "Ardmore" },
          { id: "clevedon", name: "Clevedon" },
          { id: "conifer grove", name: "Conifer Grove" },
          { id: "drury", name: "Drury" },
          { id: "hunua", name: "Hunua" },
          { id: "karaka", name: "Karaka" },
          { id: "manurewa", name: "Manurewa" },
          { id: "opaheke", name: "Opaheke" },
          { id: "pahurehure", name: "Pahurehure" },
          { id: "papakura", name: "Papakura" },
          { id: "ramarama", name: "Ramarama" },
          { id: "randwick park", name: "Randwick Park" },
          { id: "red hill", name: "Red Hill" },
          { id: "rosehill", name: "Rosehill" },
          { id: "runciman", name: "Runciman" },
          { id: "stanley point", name: "Stanley Point" },
          { id: "takanini", name: "Takanini" }
        ]
      },
      {
        id: "auckland-franklin",
        name: "Auckland - Franklin",
        suburbs: [
          { id: "ararimu", name: "Ararimu" },
          { id: "awhitu", name: "Awhitu" },
          { id: "bombay", name: "Bombay" },
          { id: "buckland", name: "Buckland" },
          { id: "clarks beach", name: "Clarks Beach" },
          { id: "clevedon", name: "Clevedon" },
          { id: "glenbrook", name: "Glenbrook" },
          { id: "greenlane", name: "Greenlane" },
          { id: "hunua", name: "Hunua" },
          { id: "karaka", name: "Karaka" },
          { id: "karioitahi", name: "Karioitahi" },
          { id: "kingseat", name: "Kingseat" },
          { id: "lake puketi", name: "Lake Puketi" },
          { id: "mangatawhiri", name: "Mangatawhiri" },
          { id: "manukau heads", name: "Manukau Heads" },
          { id: "mauku", name: "Mauku" },
          { id: "onehunga", name: "Onehunga" },
          { id: "paerata", name: "Paerata" },
          { id: "patumahoe", name: "Patumahoe" },
          { id: "pollok", name: "Pollok" },
          { id: "pukekohe", name: "Pukekohe" },
          { id: "pukekohe east", name: "Pukekohe East" },
          { id: "puni", name: "Puni" },
          { id: "ramarama", name: "Ramarama" },
          { id: "runciman", name: "Runciman" },
          { id: "swanson", name: "Swanson" },
          { id: "waiau pa", name: "Waiau Pa" },
          { id: "waiuku", name: "Waiuku" },
          { id: "whakatiwai", name: "Whakatiwai" }
        ]
      },
      {
        id: "auckland-rodney",
        name: "Auckland - Rodney",
        suburbs: [
          { id: "algies bay", name: "Algies Bay" },
          { id: "arkles bay", name: "Arkles Bay" },
          { id: "army bay", name: "Army Bay" },
          { id: "big omaha", name: "Big Omaha" },
          { id: "coatesville", name: "Coatesville" },
          { id: "dairy flat", name: "Dairy Flat" },
          { id: "dome forest", name: "Dome Forest" },
          { id: "dome valley", name: "Dome Valley" },
          { id: "glorit", name: "Glorit" },
          { id: "greenlane", name: "Greenlane" },
          { id: "gulf harbour", name: "Gulf Harbour" },
          { id: "hatfields beach", name: "Hatfields Beach" },
          { id: "helensville", name: "Helensville" },
          { id: "huapai", name: "Huapai" },
          { id: "kaipara flats", name: "Kaipara Flats" },
          { id: "kaiwaka", name: "Kaiwaka" },
          { id: "kaukapakapa", name: "Kaukapakapa" },
          { id: "kawau island", name: "Kawau Island" },
          { id: "kawau parua inlet", name: "Kawau Parua Inlet" },
          { id: "kelston", name: "Kelston" },
          { id: "kumeu", name: "Kumeu" },
          { id: "leigh", name: "Leigh" },
          { id: "mahurangi east", name: "Mahurangi East" },
          { id: "mahurangi west", name: "Mahurangi West" },
          { id: "makarau", name: "Makarau" },
          { id: "mangakura", name: "Mangakura" },
          { id: "mangawhai", name: "Mangawhai" },
          { id: "manly", name: "Manly" },
          { id: "massey", name: "Massey" },
          { id: "matakana", name: "Matakana" },
          { id: "matakatia", name: "Matakatia" },
          { id: "mount eden", name: "Mount Eden" },
          { id: "muriwai", name: "Muriwai" },
          { id: "okura bush", name: "Okura Bush" },
          { id: "omaha", name: "Omaha" },
          { id: "oratia", name: "Oratia" },
          { id: "orewa", name: "Orewa" },
          { id: "otara", name: "Otara" },
          { id: "pakiri", name: "Pakiri" },
          { id: "arakai", name: "Parakai" },
          { id: "pohuehue", name: "Pohuehue" },
          { id: "point wells", name: "Point Wells" },
          { id: "port albert", name: "Port Albert" },
          { id: "puhoi", name: "Puhoi" },
          { id: "red beach", name: "Red Beach" },
          { id: "redvale", name: "Redvale" },
          { id: "riverhead", name: "Riverhead" },
          { id: "sandspit", name: "Sandspit" },
          { id: "shelly beach", name: "Shelly Beach" },
          { id: "silverdale", name: "Silverdale" },
          { id: "snells beach", name: "Snells Beach" },
          { id: "south head", name: "South Head" },
          { id: "stanmore bay", name: "Stanmore Bay" },
          { id: "stillwater", name: "Stillwater" },
          { id: "tahekeroa", name: "Tahekeroa" },
          { id: "tapora", name: "Tapora" },
          { id: "tauhoa", name: "Tauhoa" },
          { id: "taupaki", name: "Taupaki" },
          { id: "tawharanui peninsula", name: "Tawharanui Peninsula" },
          { id: "te arai", name: "Te Arai" },
          { id: "te hana", name: "Te Hana" },
          { id: "ti point", name: "Ti Point" },
          { id: "tindalls beach", name: "Tindalls Beach" },
          { id: "tomarata", name: "Tomarata" },
          { id: "topuni", name: "Topuni" },
          { id: "wade heads", name: "Wade Heads" },
          { id: "waimauku", name: "Waimauku" },
          { id: "wainui", name: "Wainui" },
          { id: "waitakere", name: "Waitakere" },
          { id: "waitoki", name: "Waitoki" },
          { id: "waiwera", name: "Waiwera" },
          { id: "warkworth", name: "Warkworth" },
          { id: "wellsford", name: "Wellsford" },
          { id: "whangaripo", name: "Whangaripo" },
          { id: "whangateau", name: "Whangateau" },
          { id: "wharehine", name: "Wharehine" }
        ]
      },
      {
        id: "auckland-manukau",
        name: "Auckland - Manukau",
        suburbs: [
          { id: "alfriston", name: "Alfriston" },
          { id: "ardmore", name: "Ardmore" },
          { id: "beachlands", name: "Beachlands" },
          { id: "botany downs", name: "Botany Downs" },
          { id: "brookby", name: "Brookby" },
          { id: "bucklands beach", name: "Bucklands Beach" },
          { id: "burswood", name: "Burswood" },
          { id: "clendon park", name: "Clendon Park" },
          { id: "clevedon", name: "Clevedon" },
          { id: "clover park", name: "Clover Park" },
          { id: "cockle bay", name: "Cockle Bay" },
          { id: "dannemora", name: "Dannemora" },
          { id: "east tamaki", name: "East Tamaki" },
          { id: "east tamaki heights", name: "East Tamaki Heights" },
          { id: "eastern beach", name: "Eastern Beach" },
          { id: "farm cove", name: "Farm Cove" },
          { id: "favona", name: "Favona" },
          { id: "flat bush", name: "Flat Bush" },
          { id: "golflands", name: "Golflands" },
          { id: "goodwood heights", name: "Goodwood Heights" },
          { id: "half moon bay", name: "Half Moon Bay" },
          { id: "hauraki", name: "Hauraki" },
          { id: "highland park", name: "Highland Park" },
          { id: "hillcrest", name: "Hillcrest" },
          { id: "hillpark", name: "Hillpark" },
          { id: "howick", name: "Howick" },
          { id: "huntington park", name: "Huntington Park" },
          { id: "kawakawa bay", name: "Kawakawa Bay" },
          { id: "mangere", name: "Mangere" },
          { id: "mangere bridge", name: "Mangere Bridge" },
          { id: "mangere east", name: "Mangere East" },
          { id: "manukau", name: "Manukau" },
          { id: "manurewa", name: "Manurewa" },
          { id: "manurewa east", name: "Manurewa East" },
          { id: "maraetai", name: "Maraetai" },
          { id: "mellons bay", name: "Mellons Bay" },
          { id: "middlemore hospital", name: "Middlemore Hospital" },
          { id: "mount eden", name: "Mount Eden" },
          { id: "murrays bay", name: "Murrays Bay" },
          { id: "ness valley", name: "Ness Valley" },
          { id: "northpark", name: "Northpark" },
          { id: "orere point", name: "Orere Point" },
          { id: "orewa", name: "Orewa" },
          { id: "otahuhu", name: "Otahuhu" },
          { id: "otara", name: "Otara" },
          { id: "pahurehure", name: "Pahurehure" },
          { id: "pakuranga", name: "Pakuranga" },
          { id: "pakuranga heights", name: "Pakuranga Heights" },
          { id: "panmure", name: "Panmure" },
          { id: "papakura", name: "Papakura" },
          { id: "papatoetoe", name: "Papatoetoe" },
          { id: "randwick park", name: "Randwick Park" },
          { id: "shamrock park", name: "Shamrock Park" },
          { id: "shelly park", name: "Shelly Park" },
          { id: "somerville", name: "Somerville" },
          { id: "sunnyhills", name: "Sunnyhills" },
          { id: "takanini", name: "Takanini" },
          { id: "the gardens", name: "The Gardens" },
          { id: "totara heights", name: "Totara Heights" },
          { id: "totara park", name: "Totara Park" },
          { id: "wairau valley", name: "Wairau Valley" },
          { id: "wattle downs", name: "Wattle Downs" },
          { id: "weymouth", name: "Weymouth" },
          { id: "whitford", name: "Whitford" },
          { id: "wiri", name: "Wiri" }
        ]
      },
      {
        id: "auckland-waitakere",
        name: "Auckland - Waitakere",
        suburbs: [
          { id: "anawhata", name: "Anawhata" },
          { id: "blockhouse bay", name: "Blockhouse Bay" },
          { id: "cornwallis", name: "Cornwallis" },
          { id: "glen eden", name: "Glen Eden" },
          { id: "glendene", name: "Glendene" },
          { id: "green bay", name: "Green Bay" },
          { id: "henderson", name: "Henderson" },
          { id: "henderson valley", name: "Henderson Valley" },
          { id: "herald island", name: "Herald Island" },
          { id: "hobsonville", name: "Hobsonville" },
          { id: "huia", name: "Huia" },
          { id: "karekare", name: "Karekare" },
          { id: "kelston", name: "Kelston" },
          { id: "laingholm", name: "Laingholm" },
          { id: "massey", name: "Massey" },
          { id: "new lynn", name: "New Lynn" },
          { id: "oratia", name: "Oratia" },
          { id: "parau", name: "Parau" },
          { id: "piha", name: "Piha" },
          { id: "ranui", name: "Ranui" },
          { id: "sunnyvale", name: "Sunnyvale" },
          { id: "swanson", name: "Swanson" },
          { id: "te atatu peninsula", name: "Te Atatu Peninsula" },
          { id: "te atatu south", name: "Te Atatu South" },
          { id: "te henga", name: "Te Henga / Bethells Beach" },
          { id: "titirangi", name: "Titirangi" },
          { id: "waiatarua", name: "Waiatarua" },
          { id: "waitakere", name: "Waitakere" },
          { id: "west harbour", name: "West Harbour" },
          { id: "westgate", name: "Westgate" },
          { id: "whenuapai", name: "Whenuapai" }
        ]
      }
    ]
  }
];

export async function GET() {
  try {
    return NextResponse.json(regionsData);
  } catch (error) {
    console.error('Failed to fetch regions:', error);
    return NextResponse.json(
      { error: 'Failed to fetch regions' }, 
      { status: 500 }
    );
  }
}