name: Create GitHub Project Stories

on:
  push:
    branches:
      - main
    paths:
      - 'stories/**'

jobs:
  create-stories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Get changed story files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            stories/**/*.md
          separator: " "
          
      - name: Debug changed files info
        run: |
          echo "[DEBUG] Any changed files: ${{ steps.changed-files.outputs.any_changed }}" >> create-project-stories.log
          echo "[DEBUG] All changed files: ${{ steps.changed-files.outputs.all_changed_files }}" >> create-project-stories.log
          echo "[DEBUG] Added files: ${{ steps.changed-files.outputs.added_files }}" >> create-project-stories.log
          echo "[DEBUG] Modified files: ${{ steps.changed-files.outputs.modified_files }}" >> create-project-stories.log
          echo "[DEBUG] Removed files: ${{ steps.changed-files.outputs.removed_files }}" >> create-project-stories.log
          
      - name: Prepare log file
        run: |
          echo "Create GitHub Project Stories workflow started at $(date)" > create-project-stories.log
          echo "Commit SHA: ${{ github.sha }}" >> create-project-stories.log
          echo "Ref: ${{ github.ref }}" >> create-project-stories.log
          echo "Event name: ${{ github.event_name }}" >> create-project-stories.log
          echo "Any changed: ${{ steps.changed-files.outputs.any_changed }}" >> create-project-stories.log
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}" >> create-project-stories.log
          
      - name: List stories directory
        run: |
          echo "[DEBUG] Listing stories directory contents:" >> create-project-stories.log
          ls -la stories/ >> create-project-stories.log 2>&1 || echo "[DEBUG] stories directory does not exist" >> create-project-stories.log
          
      - name: Create GitHub Project Stories
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          echo "[DEBUG] Starting project item creation process at $(date)" >> create-project-stories.log
          echo "[DEBUG] Project ID: $PROJECT_ID" >> create-project-stories.log
          echo "[DEBUG] Changed files: ${{ steps.changed-files.outputs.all_changed_files }}" >> create-project-stories.log
          
          # Check if any story files changed
          CHANGED_FILES_OUTPUT="${{ steps.changed-files.outputs.all_changed_files }}"
          
          if [ -z "$CHANGED_FILES_OUTPUT" ] || [ "${{ steps.changed-files.outputs.any_changed }}" != "true" ]; then
            echo "[INFO] No changed files detected, processing all story files" >> create-project-stories.log
            ALL_STORY_FILES=$(find stories -name "*.md" -type f 2>/dev/null | tr '\n' ' ' | sed 's/ $//')
            echo "[DEBUG] All story files: $ALL_STORY_FILES" >> create-project-stories.log
            export CHANGED_FILES="$ALL_STORY_FILES"
          else
            echo "[INFO] Changed files detected: $CHANGED_FILES_OUTPUT" >> create-project-stories.log
            export CHANGED_FILES="$CHANGED_FILES_OUTPUT"
          fi
          
          echo "[DEBUG] Final CHANGED_FILES: $CHANGED_FILES" >> create-project-stories.log
          
          # Prepare artifacts directory first
          mkdir -p ./artifacts
          
          # Install required dependencies
          echo "[DEBUG] Installing dependencies" >> create-project-stories.log
          npm install marked graphql-request graphql tsx >> create-project-stories.log 2>&1
          
          # Copy the script to artifacts
          cp .github/workflows/create-project-items.ts ./artifacts/
          
          # Execute the script with required environment variables
          echo "[DEBUG] Executing TypeScript script" >> create-project-stories.log
          npx tsx .github/workflows/create-project-items.ts 2>&1 | tee -a create-project-stories.log | tee ./artifacts/run.log
          echo "[DEBUG] TypeScript script execution completed" >> create-project-stories.log
          
          echo "Logs uploaded to artifacts directory" > ./artifacts/artifact-info.txt
          echo "Changed files: $CHANGED_FILES" >> ./artifacts/artifact-info.txt
          
          echo "Artifacts ready in ./artifacts"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Create-GitHub-Project-Stories-${{ github.run_number }}
          path: |
            create-project-stories.log
            ./artifacts
          if-no-files-found: warn
          retention-days: 7